import {chromium} from '@playwright/test';
import {PDFDocument} from 'pdf-lib';
import {zipSync,unzipSync,strToU8} from 'fflate';
import {readFile,mkdir} from 'node:fs/promises';
import assert from 'node:assert/strict';
await mkdir('tmp',{recursive:true});
const original=await PDFDocument.create();original.addPage([220,400]);const pdf=Buffer.from(await original.save());
const docx=Buffer.from(zipSync({'_rels/.rels':strToU8('<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>'),'word/_rels/document.xml.rels':strToU8('<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"/>'),'word/document.xml':strToU8('<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body><w:p><w:commentRangeStart w:id="0"/><w:r><w:t>Eindeutige Textstelle</w:t></w:r><w:commentRangeEnd w:id="0"/></w:p><w:sectPr><w:pgSz w:w="11906" w:h="16838"/></w:sectPr></w:body></w:document>'),'word/comments.xml':strToU8('<w:comments xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:comment w:id="0" w:author="Lehrperson"><w:p><w:r><w:t>Dieser Kommentar bleibt vollständig erhalten.</w:t></w:r></w:p></w:comment></w:comments>')}));
const browser=await chromium.launch({channel:'chrome'}),page=await browser.newPage();const errors=[];let conversionRequests=0;page.on('pageerror',e=>errors.push(e.message));
await page.route('**/api/word/**',r=>{conversionRequests++;return r.abort()});
await page.goto(process.env.APP_URL||'http://127.0.0.1:5186/');
assert.equal(await page.getByText('Word-Ausgabe für Mac herunterladen',{exact:true}).count(),0);
await page.locator('#cover').uncheck();
const done=page.waitForEvent('download',{timeout:60000});await page.locator('#files').setInputFiles([{name:'S4d_AnnaMeier_Fehlerliste.pdf',mimeType:'application/pdf',buffer:pdf},{name:'S4d_AnnaMeier_mit_Randbemerkungen.docx',mimeType:'application/octet-stream',buffer:docx},{name:'S4d_AnnaMeier_mit_Randbemerkungen-korrektur.docx',mimeType:'application/octet-stream',buffer:docx}]);await(await done).saveAs('tmp/browser-layout.zip');
const archive=unzipSync(await readFile('tmp/browser-layout.zip'));const output=await PDFDocument.load(Object.entries(archive).find(([name])=>name.endsWith('.pdf'))[1]);
assert.equal(output.getPageCount(),3);assert.equal(output.getPage(0).getWidth(),220);assert.ok(output.getPage(1).getWidth()>800,'Comment margin must be present');assert.ok(output.getPage(1).getHeight()>840,'A4 height must be retained');assert.equal(conversionRequests,0);assert.equal(await page.locator('iframe[aria-hidden]').count(),0);assert.deepEqual(errors,[]);
await browser.close();console.log(JSON.stringify({browserOnly:true,automaticZip:true,wordInstallationNeeded:false,commentsInMargin:true,originalPdfSize:true,iframeCleanup:true}));
