import './style.css';
import {importFile} from './importer.js';
import {safeName,validateProject} from './model.js';
import {zipSync,strToU8} from 'fflate';
const app=document.querySelector('#app');
const labels={errors:'Fehlerliste',text:'Korrigierter Text',comments:'Kommentare'};
const uid=()=>crypto.randomUUID();
const fresh=()=>({id:uid(),title:'Neues Dossier',person:'',group:'',date:new Date().toLocaleDateString('sv-SE'),sources:[],cover:true});
let dossiers=[fresh()],active=dossiers[0].id,tab='errors',busy=false;
const drafts=new Map();
const current=()=>dossiers.find(d=>d.id===active);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const count=(d,k)=>d.sources.filter(s=>s.kind===k).length;
function render(){const d=current();app.innerHTML=`
<header class="top"><div class="brand"><span class="mark">≡</span>Dossier<span><small>Korrekturen zusammenführen</small></span></div><div class="privacy">◈ &nbsp; Verarbeitung auf deinem Gerät</div></header>
<div class="layout"><aside><p class="eyebrow">Deine Dossiers</p><div class="dossier-list">${dossiers.map(x=>`<button class="dossier-item ${x.id===active?'active':''}" data-select="${x.id}" ${busy?'disabled':''}>${esc(x.person||x.title)}<small>${x.sources.length} Quellen · ${x.group?esc(x.group):'Noch keine Klasse'}</small></button>`).join('')}</div><div class="aside-actions"><button id="new" ${busy?'disabled':''}>＋ Neues Dossier</button><button id="save" ${busy?'disabled':''}>Projekt sichern</button><button id="open" ${busy?'disabled':''}>Projekt öffnen</button><button id="all" ${busy||!dossiers.some(x=>x.sources.length)?'disabled':''}>Alle PDFs als ZIP</button></div><p class="aside-note">Deine Inhalte bleiben in diesem Tab. Sichere das Projekt, bevor du ihn schliesst.</p></aside>
<main class="main"><div class="heading"><div><h1>Aus Korrekturen wird ein Dossier.</h1><p>Quellen sammeln, Inhalte prüfen, als PDF mitnehmen.</p></div><span class="badge">Lokal & vertraulich</span></div><div class="workflow"><span class="current"><b>1</b>Quellen sammeln</span><span><b>2</b>Inhalte prüfen</span><span><b>3</b>PDF herunterladen</span></div>
<div class="work-grid"><div><section class="panel"><h2>Angaben zum Dossier</h2><div class="fields"><label class="full">Titel<input data-field="title" value="${esc(d.title)}" placeholder="z. B. Erörterung · Rückmeldung"></label><label>Name<input data-field="person" value="${esc(d.person)}" placeholder="Vorname Nachname"></label><label>Klasse / Kurs<input data-field="group" value="${esc(d.group)}" placeholder="z. B. FMS 2a"></label><label>Datum<input type="date" data-field="date" value="${esc(d.date)}"></label></div></section>
<section class="panel"><div class="tabs" role="tablist" aria-label="Quellenart">${Object.entries(labels).map(([k,v])=>`<button role="tab" aria-selected="${tab===k}" class="${tab===k?'active':''}" data-tab="${k}">${v}<small>${count(d,k)}</small></button>`).join('')}</div><div class="drop" id="drop"><div class="drop-icon">↥</div><strong>${labels[tab]} hinzufügen</strong><p>Dateien hier ablegen oder auswählen. Mehrere Dateien sind möglich.</p><button id="upload" ${busy?'disabled':''}>${busy?'Wird verarbeitet …':'Dateien auswählen'}</button></div><div class="formats">DOCX · PDF · ODT · TXT · Markdown · CSV / TSV · HTML · JSON<br>Word-Kommentare und PDF-Anmerkungen werden mit eingelesen.</div><div id="sources">${d.sources.filter(s=>s.kind===tab).map(s=>`<article class="source"><div class="source-top"><div><div class="source-name">${esc(s.name)}</div><small>${s.original?'PDF-Original wird angehängt · ':''}${s.text.length.toLocaleString('de-CH')} Zeichen</small></div><div class="source-actions"><button data-edit="${s.id}">Prüfen</button><button data-remove="${s.id}" aria-label="${esc(s.name)} entfernen">×</button></div></div>${s.warning?`<p class="notice">${esc(s.warning)}</p>`:''}<div id="edit-${s.id}" hidden><label>Inhalt / Anmerkungen<textarea data-source="${s.id}">${esc(s.text)}</textarea></label><label>Zuordnung<select data-kind="${s.id}">${Object.entries(labels).map(([k,v])=>`<option value="${k}" ${s.kind===k?'selected':''}>${v}</option>`).join('')}</select></label></div></article>`).join('')}</div><div class="or">ODER TEXT DIREKT EINFÜGEN</div><label>Text für «${labels[tab]}»<textarea id="paste" placeholder="Auch Listen, Tabellen und kopierte Rückmeldungen sind willkommen."></textarea></label><button id="add-text" style="margin-top:10px" ${busy?'disabled':''}>Text übernehmen</button><details class="help"><summary>Was bleibt beim Import erhalten?</summary><p>Text und Tabelleninhalte werden vereinheitlicht. Word-Kommentare erscheinen mit Verweisnummern, ODT-Anmerkungen im Text. PDF-Seiten bleiben als Originalanhang erhalten; auslesbare Anmerkungen werden zusätzlich aufgeführt. Layouts aus Word werden neu gesetzt. Bilddateien, alte DOC-Dateien und Texterkennung (OCR) werden nicht unterstützt.</p></details></section></div>
<section class="panel export-panel"><p class="eyebrow">Deine Ausgabe</p><h2>Bereit für die Rückgabe.</h2><div class="paper"><div class="paper-rule"></div><small>Korrekturdossier</small><h3 id="preview-title">${esc(d.title)}</h3><p id="preview-person">${esc(d.person||'Name noch offen')}<br>${esc(d.group)}</p><div class="paper-sections">${Object.entries(labels).map(([k,v])=>`<div><span>${v}</span><span>${count(d,k)} Quellen</span></div>`).join('')}</div></div><label class="check"><input type="checkbox" id="cover" ${d.cover?'checked':''}>Deckblatt hinzufügen</label><p>${d.sources.length} Quellen · A4 · mit Seitenzahlen</p><button class="primary" id="pdf" ${busy||!d.sources.length?'disabled':''}>↓ PDF herunterladen</button><button class="quiet danger" id="delete" ${busy?'disabled':''}>Dossier entfernen</button><details class="help"><summary>Hinweise zum PDF</summary><p>Leere Bereiche werden ausgelassen. Original-PDFs folgen nach den aufbereiteten Inhalten. Prüfe den Export vor der Weitergabe.</p></details></section></div><div class="footer">Keine Anmeldung. Keine Übertragung deiner Dokumente.</div></main></div><input hidden type="file" id="files" multiple accept=".txt,.md,.markdown,.csv,.tsv,.json,.html,.htm,.docx,.odt,.pdf"><input hidden type="file" id="project" accept=".json"><div class="status" role="status" aria-live="polite" id="status"></div><dialog id="confirm"><h2>Dossier entfernen?</h2><p>Dieses Dossier mit allen eingefügten Quellen wird aus dem aktuellen Projekt entfernt.</p><div class="dialog-actions"><button id="cancel">Abbrechen</button><button class="danger" id="confirm-delete">Entfernen</button></div></dialog>`;bind();}
let noticeTimer;
function notify(message){clearTimeout(noticeTimer);document.querySelector('#status').textContent=message;if(!busy)noticeTimer=setTimeout(()=>{const el=document.querySelector('#status');if(el)el.textContent=''},14000);}
function bind(){
 document.querySelector('#paste').value=drafts.get(active+tab)||'';
 document.querySelector('#paste').oninput=e=>drafts.set(active+tab,e.target.value);
 document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render()});
 document.querySelectorAll('[data-select]').forEach(b=>b.onclick=()=>{active=b.dataset.select;render()});
 document.querySelectorAll('[data-field]').forEach(e=>e.oninput=()=>{current()[e.dataset.field]=e.value;document.querySelector('#preview-title').textContent=current().title;document.querySelector('#preview-person').textContent=[current().person,current().group].filter(Boolean).join(' · ')});
 document.querySelector('#new').onclick=()=>{const d=fresh();dossiers.push(d);active=d.id;render()};
 document.querySelector('#upload').onclick=()=>document.querySelector('#files').click();
 document.querySelector('#cover').onchange=e=>{current().cover=e.target.checked};
 document.querySelector('#add-text').onclick=()=>{const value=document.querySelector('#paste').value.trim();if(!value)return notify('Bitte zuerst einen Text einfügen.');current().sources.push({id:uid(),name:`${labels[tab]} · eingefügter Text`,kind:tab,text:value});drafts.delete(active+tab);render();notify('Text übernommen. Über «Prüfen» kannst du ihn bearbeiten.')};
 document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{const el=document.getElementById(`edit-${b.dataset.edit}`);el.hidden=!el.hidden;b.textContent=el.hidden?'Prüfen':'Schliessen'});
 document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{current().sources=current().sources.filter(s=>s.id!==b.dataset.remove);render()});
 document.querySelectorAll('[data-source]').forEach(e=>e.oninput=()=>{current().sources.find(s=>s.id===e.dataset.source).text=e.value});
 document.querySelectorAll('[data-kind]').forEach(e=>e.onchange=()=>{current().sources.find(s=>s.id===e.dataset.kind).kind=e.value;render()});
 document.querySelector('#delete').onclick=()=>document.querySelector('#confirm').showModal();
 document.querySelector('#cancel').onclick=()=>document.querySelector('#confirm').close();
 document.querySelector('#confirm-delete').onclick=()=>{dossiers=dossiers.filter(d=>d.id!==active);if(!dossiers.length)dossiers=[fresh()];active=dossiers[0].id;render()};
 document.querySelector('#files').onchange=e=>addFiles(e.target.files);
 const drop=document.querySelector('#drop');drop.ondragover=e=>{e.preventDefault();drop.classList.add('drag')};drop.ondragleave=()=>drop.classList.remove('drag');drop.ondrop=e=>{e.preventDefault();drop.classList.remove('drag');addFiles(e.dataTransfer.files)};
 document.querySelector('#pdf').onclick=()=>exportPdfs(false);
 document.querySelector('#all').onclick=()=>exportPdfs(true);
 document.querySelector('#save').onclick=()=>{download(strToU8(JSON.stringify({format:'korrektur-dossier',version:1,dossiers},null,2)),'Dossier-Projekt.json','application/json');notify('Projekt gesichert. Bewahre die Datei vertraulich auf.')};
 document.querySelector('#open').onclick=()=>document.querySelector('#project').click();
 document.querySelector('#project').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>150*1024*1024)throw Error('Projekt zu gross (max. 150 MB).');const loaded=validateProject(JSON.parse(await f.text()));dossiers.push(...loaded);active=loaded[0].id;render();notify(`${loaded.length} Dossiers zum Projekt hinzugefügt.`)}catch(err){notify(err.message)}};
}
async function addFiles(list){if(busy)return;const d=current(),kind=tab,files=Array.from(list);if(!files.length)return;busy=true;render();let success=0;const failed=[];
 for(const f of files){notify(`Lese ${f.name} …`);try{const parsed=await importFile(f);if(!parsed.text?.trim()&&!parsed.original)throw Error('Kein lesbarer Text gefunden.');d.sources.push({id:uid(),name:f.name,kind,...parsed});success++}catch(e){failed.push(`${f.name}: ${e.message}`)}}
 busy=false;render();notify(`${success} Datei${success===1?'':'en'} übernommen.${failed.length?' '+failed.join(' | '):' Inhalte unter «Prüfen» kontrollieren.'}`);
}
function download(bytes,name,type){const url=URL.createObjectURL(new Blob([bytes],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000)}
async function exportPdfs(all){if(busy)return;const selection=structuredClone(all?dossiers.filter(d=>d.sources.length):[current()]);busy=true;render();notify('PDF wird erstellt …');try{const {createPdf}=await import('./pdf.js');if(all){const files={};for(let i=0;i<selection.length;i++){const d=selection[i];notify(`Dossier ${i+1} von ${selection.length} wird erstellt …`);files[`${String(i+1).padStart(2,'0')}-${safeName(d.person||d.title)}.pdf`]=await createPdf(d)}download(zipSync(files,{level:0}),'Korrektur-Dossiers.zip','application/zip')}else{const d=selection[0];download(await createPdf(d),`${safeName([d.person,d.title].filter(Boolean).join(' - '))}.pdf`,'application/pdf')}busy=false;render();notify('Download erstellt. Bitte das PDF vor der Weitergabe prüfen.')}catch(e){busy=false;render();notify(`Export nicht möglich: ${e.message}`)}}
window.addEventListener('beforeunload',e=>{if(dossiers.some(d=>d.sources.length)||[...drafts.values()].some(Boolean)){e.preventDefault();e.returnValue=''}});
render();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'read_dossier_overview',description:'Liest Namen und Quellenanzahl der geöffneten Dossiers, ohne Dokumentinhalte zu übertragen.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:input=>{if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw Error('Leeres Objekt erwartet.');return {dossiers:dossiers.map(d=>({id:d.id,title:d.title,person:d.person,sources:d.sources.length})),active}}})).catch(()=>{})}catch{}}
